---
- name: Set yum repository for the nginx
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo mode=0644 owner=root group=root
  notify: yum update

- name: Install nginx
  yum: name=nginx state=present

- name: Copy nginx configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
