# https://github.com/William-Yeh/ansible-fluentd/blob/master/test/Dockerfile-centos6
---

language: python
python: "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl
script:
  - echo localhost > inventory
  - ansible-galaxy install --role-file=role_packages.yml
  - ansible-playbook --syntax-check -i inventory site.yml
