---

- name: Initialize sshd_config and sudors
  hosts: centos6_init
  remote_user: root
  become: yes
  vars_prompt:
    - name: admin_password
      prompt: Admin user's password
      private: yes
      confirm: yes
      when: admin_password == "" or admin_password is undefined
  roles:
    - common
    - users
    - sshd_config

- name: Be sure to exist admin user
  hosts: wordpress_server
  remote_user: root
  become: yes
  vars_prompt:
    - name: admin_password
      prompt: Admin user's password
      private: yes
      confirm: yes
      when: admin_password == "" or admin_password is undefined
  roles:
    - common
    - users

- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: wordpress_server
  remote_user: admin
  become: yes
  vars_prompt:
      - name: mysql_root_password
        prompt: MySQL Root User's Password
        private: yes
        confirm: yes
        when: mysql_root_password == "" or mysql_root_password is undefined
      - name: wp_db_password
        prompt: WordPress Database's Password
        private: yes
        confirm: yes
        when: wp_db_password == "" or wp_db_password is undefined
      - name: newrelic_license_key
        prompt: NewRelic's License Key
        private: yes
        confirm: yes
        when: newrelic_license_key == "" or newrelic_license_key is undefined
  roles:
    - common
    - mysql
    - nginx
    - php-fpm
    - wordpress
    - monitoring
    - resmo.fail2ban
    - williamyeh.fluentd
    - sivel.newrelic
    - nleutner.newrelic-php
    - geerlingguy.postfix
    - yatesr.timezone
