---

- name: Install Mysql packages
  yum: name={{ mysql_url }}/{{ item }}-{{ mysql_ver }}.rpm state=present
  with_items:
    - MySQL-client
    - MySQL-shared-compat
    - MySQL-shared
    - MySQL-devel
    - MySQL-embedded
    - MySQL-server

- name: Install other packages
  yum: name={{ item }} state=present
  with_items:
    - MySQL-python
    - libselinux-python
    - libsemanage-python

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: ansible_selinux == true

- name: Chown datadir
  file: path=/var/lib/mysql owner=mysql recurse=yes

- name: Create log files
  file: path={{ item.path }} owner=mysql state=touch mode="u=rw,g=r,o=r"
  with_items:
    - path: '/var/log/mysql-slow.log'
    - path: '/var/log/mysql-query.log'

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: Start Mysql Service
  service: name=mysql state=started enabled=yes

- name: Register defualt mysql password
  shell: |
    [[ -f /root/.mysql_secret ]] \
    && cat /root/.mysql_secret | awk '{print $NF}' | awk '/./'
  register: mysql_secret
  ignore_errors: True

- debug: msg="[MySQL] Defualt root password {{ mysql_secret }}"

- name: Setup mysql root password instead of default root password
  shell: |
    mysql -uroot --password={{ mysql_secret.stdout }} \
    -e "SET PASSWORD = PASSWORD('{{ mysql_root_password }}');"
  when: mysql_secret | success

- name: Purge default root password file after setting root password
  file: path=/root/.mysql_secret state=absent
  when: mysql_secret | success
