---

- name: Add repository
  yum: name={{ item }} state=present
  with_items:
    - "http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm"

- name: Install MySQL packages
  yum: name={{ item }} enablerepo="mysql56-community" state=present
  with_items:
    - mysql-community-server
  retries: 3
  delay: 10

- name: Install other packages
  yum: name={{ item }} state=present
  with_items:
    - MySQL-python
    - libselinux-python
    - libsemanage-python

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: ansible_selinux == true

- name: Chown datadir
  file: path=/var/lib/mysql owner=mysql recurse=yes

- name: Create log files
  copy: force=no src=null dest={{ item.path }} owner=mysql group=mysql mode="u=rw,g=r,o=r"
  with_items:
    - path: '/var/log/mysql-slow.log'
    - path: '/var/log/mysql-query.log'

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes

- name: Setup mysql root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    state: present

- name: Create root configuration file
  template: src=root_my.cnf.j2 dest="/root/.my.cnf" owner=root mode=0600
  notify:
  - restart mysql
