---
# meta/main.yml

galaxy_info:
    author: williamyeh
    description: Install Fluentd (td-agent version)
    license: MIT
    min_ansible_version: 1.8

    platforms:

        - name: Ubuntu
          versions:
              - precise
              - trusty

        - name: Debian
          versions:
              - wheezy
              - jessie

        - name: EL
          versions:
              - 6
              - 7

    categories:
        - system

dependencies: []
