machine:
  services:
    - docker

dependencies:
  override:
    - docker info
    - docker version

    - docker build  -f test/Dockerfile-ubuntu14.04  -t fluentd_trusty   .
    - docker build  -f test/Dockerfile-ubuntu12.04  -t fluentd_precise  .
    - docker build  -f test/Dockerfile-debian8      -t fluentd_jessie   .
    - docker build  -f test/Dockerfile-debian7      -t fluentd_wheezy   .
    - docker build  -f test/Dockerfile-centos7      -t fluentd_centos7  .
    - docker build  -f test/Dockerfile-centos6      -t fluentd_centos6  .

test:
  override:
    - docker run  -v $(pwd):/data  fluentd_trusty
    - docker run  -v $(pwd):/data  fluentd_precise
    - docker run  -v $(pwd):/data  fluentd_jessie
    - docker run  -v $(pwd):/data  fluentd_wheezy
    - docker run  -v $(pwd):/data  fluentd_centos7
    - docker run  -v $(pwd):/data  fluentd_centos6

    - echo "==> Validating the test results..."
    - grep 'monitor_agent' result-ubuntu14.04
    - grep 'monitor_agent' result-ubuntu12.04
    - grep 'monitor_agent' result-debian8
    - grep 'monitor_agent' result-debian7
    - grep 'monitor_agent' result-centos7
    - grep 'monitor_agent' result-centos6
