---
# file: tasks/set-role-variables.yml
# set necessary role variables.
#

- name: set tdagent_use_service = True, if not defined
  set_fact:
    tdagent_use_service: True
  when: tdagent_use_service is not defined
